language: cpp
compiler:
    - gcc

script:
    ./build.sh


install:
    echo  "Uncomment when travis supports ubuntu 14.04"
    #git submodule init;
    #git submodule update;
    #cd thirdparty;
    #./install_sysdeps.sh;
    #./install_ros.sh;
    #./install_gazebo.sh;
    #./install_gpstk.sh;
    #source /opt/ros/indigo/setup.bash;
    #cd ../;
