(cl:in-package hal_quadrotor-msg)
(cl:export '(T-VAL
          T
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          U-VAL
          U
          V-VAL
          V
          W-VAL
          W
          P-VAL
          P
          Q-VAL
          Q
          R-VAL
          R
          THRUST-VAL
          THRUST
          REMAINING-VAL
          REMAINING
))