/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/asymingt/Workspace/Source/crates/src/hal_sensor_imu/srv/Configure.srv
 *
 */


#ifndef HAL_SENSOR_IMU_MESSAGE_CONFIGURE_H
#define HAL_SENSOR_IMU_MESSAGE_CONFIGURE_H

#include <ros/service_traits.h>


#include <hal_sensor_imu/ConfigureRequest.h>
#include <hal_sensor_imu/ConfigureResponse.h>


namespace hal_sensor_imu
{

struct Configure
{

typedef ConfigureRequest Request;
typedef ConfigureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Configure
} // namespace hal_sensor_imu


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hal_sensor_imu::Configure > {
  static const char* value()
  {
    return "c138d47fe339d97761e69b77ee1c1cd5";
  }

  static const char* value(const ::hal_sensor_imu::Configure&) { return value(); }
};

template<>
struct DataType< ::hal_sensor_imu::Configure > {
  static const char* value()
  {
    return "hal_sensor_imu/Configure";
  }

  static const char* value(const ::hal_sensor_imu::Configure&) { return value(); }
};


// service_traits::MD5Sum< ::hal_sensor_imu::ConfigureRequest> should match 
// service_traits::MD5Sum< ::hal_sensor_imu::Configure > 
template<>
struct MD5Sum< ::hal_sensor_imu::ConfigureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hal_sensor_imu::Configure >::value();
  }
  static const char* value(const ::hal_sensor_imu::ConfigureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hal_sensor_imu::ConfigureRequest> should match 
// service_traits::DataType< ::hal_sensor_imu::Configure > 
template<>
struct DataType< ::hal_sensor_imu::ConfigureRequest>
{
  static const char* value()
  {
    return DataType< ::hal_sensor_imu::Configure >::value();
  }
  static const char* value(const ::hal_sensor_imu::ConfigureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hal_sensor_imu::ConfigureResponse> should match 
// service_traits::MD5Sum< ::hal_sensor_imu::Configure > 
template<>
struct MD5Sum< ::hal_sensor_imu::ConfigureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hal_sensor_imu::Configure >::value();
  }
  static const char* value(const ::hal_sensor_imu::ConfigureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hal_sensor_imu::ConfigureResponse> should match 
// service_traits::DataType< ::hal_sensor_imu::Configure > 
template<>
struct DataType< ::hal_sensor_imu::ConfigureResponse>
{
  static const char* value()
  {
    return DataType< ::hal_sensor_imu::Configure >::value();
  }
  static const char* value(const ::hal_sensor_imu::ConfigureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAL_SENSOR_IMU_MESSAGE_CONFIGURE_H
