/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/asymingt/Workspace/Source/crates/src/hal_quadrotor/srv/SetControl.srv
 *
 */


#ifndef HAL_QUADROTOR_MESSAGE_SETCONTROLREQUEST_H
#define HAL_QUADROTOR_MESSAGE_SETCONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hal_quadrotor/Control.h>

namespace hal_quadrotor
{
template <class ContainerAllocator>
struct SetControlRequest_
{
  typedef SetControlRequest_<ContainerAllocator> Type;

  SetControlRequest_()
    : control()  {
    }
  SetControlRequest_(const ContainerAllocator& _alloc)
    : control(_alloc)  {
    }



   typedef  ::hal_quadrotor::Control_<ContainerAllocator>  _control_type;
  _control_type control;




  typedef boost::shared_ptr< ::hal_quadrotor::SetControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hal_quadrotor::SetControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetControlRequest_

typedef ::hal_quadrotor::SetControlRequest_<std::allocator<void> > SetControlRequest;

typedef boost::shared_ptr< ::hal_quadrotor::SetControlRequest > SetControlRequestPtr;
typedef boost::shared_ptr< ::hal_quadrotor::SetControlRequest const> SetControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hal_quadrotor::SetControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hal_quadrotor::SetControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hal_quadrotor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'hal_quadrotor': ['/home/asymingt/Workspace/Source/crates/src/hal_quadrotor/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hal_quadrotor::SetControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hal_quadrotor::SetControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hal_quadrotor::SetControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hal_quadrotor::SetControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hal_quadrotor::SetControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hal_quadrotor::SetControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hal_quadrotor::SetControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6439669a77b695ef3067ee69a1face7";
  }

  static const char* value(const ::hal_quadrotor::SetControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6439669a77b695eULL;
  static const uint64_t static_value2 = 0xf3067ee69a1face7ULL;
};

template<class ContainerAllocator>
struct DataType< ::hal_quadrotor::SetControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hal_quadrotor/SetControlRequest";
  }

  static const char* value(const ::hal_quadrotor::SetControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hal_quadrotor::SetControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hal_quadrotor/Control control\n\
\n\
================================================================================\n\
MSG: hal_quadrotor/Control\n\
float64 t	    	# Time stamp\n\
float64 roll     	# Body-frame X ROLL\n\
float64 pitch     	# Body-frame Y PITCH\n\
float64 yaw     	# Body-frame Z YAW\n\
float64 throttle    # Body-frame THROTTLE\n\
";
  }

  static const char* value(const ::hal_quadrotor::SetControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hal_quadrotor::SetControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hal_quadrotor::SetControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hal_quadrotor::SetControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "control: ";
    s << std::endl;
    Printer< ::hal_quadrotor::Control_<ContainerAllocator> >::stream(s, indent + "  ", v.control);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAL_QUADROTOR_MESSAGE_SETCONTROLREQUEST_H
