/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/asymingt/Workspace/Source/crates/src/hal_quadrotor/msg/State.msg
 *
 */


#ifndef HAL_QUADROTOR_MESSAGE_STATE_H
#define HAL_QUADROTOR_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hal_quadrotor
{
template <class ContainerAllocator>
struct State_
{
  typedef State_<ContainerAllocator> Type;

  State_()
    : t(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , u(0.0)
    , v(0.0)
    , w(0.0)
    , p(0.0)
    , q(0.0)
    , r(0.0)
    , thrust(0.0)
    , remaining(0.0)  {
    }
  State_(const ContainerAllocator& _alloc)
    : t(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , u(0.0)
    , v(0.0)
    , w(0.0)
    , p(0.0)
    , q(0.0)
    , r(0.0)
    , thrust(0.0)
    , remaining(0.0)  {
    }



   typedef double _t_type;
  _t_type t;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _u_type;
  _u_type u;

   typedef double _v_type;
  _v_type v;

   typedef double _w_type;
  _w_type w;

   typedef double _p_type;
  _p_type p;

   typedef double _q_type;
  _q_type q;

   typedef double _r_type;
  _r_type r;

   typedef double _thrust_type;
  _thrust_type thrust;

   typedef double _remaining_type;
  _remaining_type remaining;




  typedef boost::shared_ptr< ::hal_quadrotor::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hal_quadrotor::State_<ContainerAllocator> const> ConstPtr;

}; // struct State_

typedef ::hal_quadrotor::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::hal_quadrotor::State > StatePtr;
typedef boost::shared_ptr< ::hal_quadrotor::State const> StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hal_quadrotor::State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hal_quadrotor::State_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hal_quadrotor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'hal_quadrotor': ['/home/asymingt/Workspace/Source/crates/src/hal_quadrotor/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hal_quadrotor::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hal_quadrotor::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hal_quadrotor::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hal_quadrotor::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hal_quadrotor::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hal_quadrotor::State_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hal_quadrotor::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd7ae38fc9e37befb212bfebfefaf134";
  }

  static const char* value(const ::hal_quadrotor::State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd7ae38fc9e37befULL;
  static const uint64_t static_value2 = 0xb212bfebfefaf134ULL;
};

template<class ContainerAllocator>
struct DataType< ::hal_quadrotor::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hal_quadrotor/State";
  }

  static const char* value(const ::hal_quadrotor::State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hal_quadrotor::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 t	    	# Time stamp\n\
float64 x	    	# n-frame X position (X == +East)\n\
float64 y	   		# n-frame Y position (Y == +North)\n\
float64 z	    	# n-frame Z position (Z == +Up)\n\
float64 roll	    # n-frame roll (anti-clockwise about X)\n\
float64 pitch	    # n-frame pitch (anti-clockwise about Y)\n\
float64 yaw	    	# n-frame yaw (anti-clockwise about Z)\n\
float64 u	    	# b-frame X velocity\n\
float64 v	    	# b-frame Y velocity\n\
float64 w	    	# b-frame Z velocity\n\
float64 p	    	# b-frame roll angular velocity\n\
float64 q	    	# b-frame pitch angular velocity\n\
float64 r	    	# b-frame yaw angular velocity\n\
float64 thrust	    # Current thrust force\n\
float64 remaining	# Flight time remaining\n\
";
  }

  static const char* value(const ::hal_quadrotor::State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hal_quadrotor::State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.t);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.u);
      stream.next(m.v);
      stream.next(m.w);
      stream.next(m.p);
      stream.next(m.q);
      stream.next(m.r);
      stream.next(m.thrust);
      stream.next(m.remaining);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hal_quadrotor::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hal_quadrotor::State_<ContainerAllocator>& v)
  {
    s << indent << "t: ";
    Printer<double>::stream(s, indent + "  ", v.t);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "u: ";
    Printer<double>::stream(s, indent + "  ", v.u);
    s << indent << "v: ";
    Printer<double>::stream(s, indent + "  ", v.v);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
    s << indent << "p: ";
    Printer<double>::stream(s, indent + "  ", v.p);
    s << indent << "q: ";
    Printer<double>::stream(s, indent + "  ", v.q);
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
    s << indent << "thrust: ";
    Printer<double>::stream(s, indent + "  ", v.thrust);
    s << indent << "remaining: ";
    Printer<double>::stream(s, indent + "  ", v.remaining);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAL_QUADROTOR_MESSAGE_STATE_H
