/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/asymingt/Workspace/Source/crates/src/hal_quadrotor/srv/Takeoff.srv
 *
 */


#ifndef HAL_QUADROTOR_MESSAGE_TAKEOFF_H
#define HAL_QUADROTOR_MESSAGE_TAKEOFF_H

#include <ros/service_traits.h>


#include <hal_quadrotor/TakeoffRequest.h>
#include <hal_quadrotor/TakeoffResponse.h>


namespace hal_quadrotor
{

struct Takeoff
{

typedef TakeoffRequest Request;
typedef TakeoffResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Takeoff
} // namespace hal_quadrotor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hal_quadrotor::Takeoff > {
  static const char* value()
  {
    return "fd827683f3053f974df19d13a876d4e5";
  }

  static const char* value(const ::hal_quadrotor::Takeoff&) { return value(); }
};

template<>
struct DataType< ::hal_quadrotor::Takeoff > {
  static const char* value()
  {
    return "hal_quadrotor/Takeoff";
  }

  static const char* value(const ::hal_quadrotor::Takeoff&) { return value(); }
};


// service_traits::MD5Sum< ::hal_quadrotor::TakeoffRequest> should match 
// service_traits::MD5Sum< ::hal_quadrotor::Takeoff > 
template<>
struct MD5Sum< ::hal_quadrotor::TakeoffRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hal_quadrotor::Takeoff >::value();
  }
  static const char* value(const ::hal_quadrotor::TakeoffRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hal_quadrotor::TakeoffRequest> should match 
// service_traits::DataType< ::hal_quadrotor::Takeoff > 
template<>
struct DataType< ::hal_quadrotor::TakeoffRequest>
{
  static const char* value()
  {
    return DataType< ::hal_quadrotor::Takeoff >::value();
  }
  static const char* value(const ::hal_quadrotor::TakeoffRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hal_quadrotor::TakeoffResponse> should match 
// service_traits::MD5Sum< ::hal_quadrotor::Takeoff > 
template<>
struct MD5Sum< ::hal_quadrotor::TakeoffResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hal_quadrotor::Takeoff >::value();
  }
  static const char* value(const ::hal_quadrotor::TakeoffResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hal_quadrotor::TakeoffResponse> should match 
// service_traits::DataType< ::hal_quadrotor::Takeoff > 
template<>
struct DataType< ::hal_quadrotor::TakeoffResponse>
{
  static const char* value()
  {
    return DataType< ::hal_quadrotor::Takeoff >::value();
  }
  static const char* value(const ::hal_quadrotor::TakeoffResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAL_QUADROTOR_MESSAGE_TAKEOFF_H
