"""autogenerated by genpy from hal_quadrotor/GetTruthRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GetTruthRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "hal_quadrotor/GetTruthRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetTruthRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
"""autogenerated by genpy from hal_quadrotor/GetTruthResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import hal_quadrotor.msg

class GetTruthResponse(genpy.Message):
  _md5sum = "f2033d5defdcc91d37ab097f3c9ec53b"
  _type = "hal_quadrotor/GetTruthResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """hal_quadrotor/State state

================================================================================
MSG: hal_quadrotor/State
float64 t	    	# Time stamp
float64 x	    	# n-frame X position (X == +East)
float64 y	   		# n-frame Y position (Y == +North)
float64 z	    	# n-frame Z position (Z == +Up)
float64 roll	    # n-frame roll (anti-clockwise about X)
float64 pitch	    # n-frame pitch (anti-clockwise about Y)
float64 yaw	    	# n-frame yaw (anti-clockwise about Z)
float64 u	    	# b-frame X velocity
float64 v	    	# b-frame Y velocity
float64 w	    	# b-frame Z velocity
float64 p	    	# b-frame roll angular velocity
float64 q	    	# b-frame pitch angular velocity
float64 r	    	# b-frame yaw angular velocity
float64 thrust	    # Current thrust force
float64 remaining	# Flight time remaining
"""
  __slots__ = ['state']
  _slot_types = ['hal_quadrotor/State']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetTruthResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.state is None:
        self.state = hal_quadrotor.msg.State()
    else:
      self.state = hal_quadrotor.msg.State()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_15d.pack(_x.state.t, _x.state.x, _x.state.y, _x.state.z, _x.state.roll, _x.state.pitch, _x.state.yaw, _x.state.u, _x.state.v, _x.state.w, _x.state.p, _x.state.q, _x.state.r, _x.state.thrust, _x.state.remaining))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.state is None:
        self.state = hal_quadrotor.msg.State()
      end = 0
      _x = self
      start = end
      end += 120
      (_x.state.t, _x.state.x, _x.state.y, _x.state.z, _x.state.roll, _x.state.pitch, _x.state.yaw, _x.state.u, _x.state.v, _x.state.w, _x.state.p, _x.state.q, _x.state.r, _x.state.thrust, _x.state.remaining,) = _struct_15d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_15d.pack(_x.state.t, _x.state.x, _x.state.y, _x.state.z, _x.state.roll, _x.state.pitch, _x.state.yaw, _x.state.u, _x.state.v, _x.state.w, _x.state.p, _x.state.q, _x.state.r, _x.state.thrust, _x.state.remaining))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.state is None:
        self.state = hal_quadrotor.msg.State()
      end = 0
      _x = self
      start = end
      end += 120
      (_x.state.t, _x.state.x, _x.state.y, _x.state.z, _x.state.roll, _x.state.pitch, _x.state.yaw, _x.state.u, _x.state.v, _x.state.w, _x.state.p, _x.state.q, _x.state.r, _x.state.thrust, _x.state.remaining,) = _struct_15d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_15d = struct.Struct("<15d")
class GetTruth(object):
  _type          = 'hal_quadrotor/GetTruth'
  _md5sum = 'f2033d5defdcc91d37ab097f3c9ec53b'
  _request_class  = GetTruthRequest
  _response_class = GetTruthResponse
