"""autogenerated by genpy from hal_quadrotor/SetEstimateRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import hal_quadrotor.msg

class SetEstimateRequest(genpy.Message):
  _md5sum = "f2033d5defdcc91d37ab097f3c9ec53b"
  _type = "hal_quadrotor/SetEstimateRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """hal_quadrotor/State state

================================================================================
MSG: hal_quadrotor/State
float64 t	    	# Time stamp
float64 x	    	# n-frame X position (X == +East)
float64 y	   		# n-frame Y position (Y == +North)
float64 z	    	# n-frame Z position (Z == +Up)
float64 roll	    # n-frame roll (anti-clockwise about X)
float64 pitch	    # n-frame pitch (anti-clockwise about Y)
float64 yaw	    	# n-frame yaw (anti-clockwise about Z)
float64 u	    	# b-frame X velocity
float64 v	    	# b-frame Y velocity
float64 w	    	# b-frame Z velocity
float64 p	    	# b-frame roll angular velocity
float64 q	    	# b-frame pitch angular velocity
float64 r	    	# b-frame yaw angular velocity
float64 thrust	    # Current thrust force
float64 remaining	# Flight time remaining
"""
  __slots__ = ['state']
  _slot_types = ['hal_quadrotor/State']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SetEstimateRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.state is None:
        self.state = hal_quadrotor.msg.State()
    else:
      self.state = hal_quadrotor.msg.State()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_15d.pack(_x.state.t, _x.state.x, _x.state.y, _x.state.z, _x.state.roll, _x.state.pitch, _x.state.yaw, _x.state.u, _x.state.v, _x.state.w, _x.state.p, _x.state.q, _x.state.r, _x.state.thrust, _x.state.remaining))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.state is None:
        self.state = hal_quadrotor.msg.State()
      end = 0
      _x = self
      start = end
      end += 120
      (_x.state.t, _x.state.x, _x.state.y, _x.state.z, _x.state.roll, _x.state.pitch, _x.state.yaw, _x.state.u, _x.state.v, _x.state.w, _x.state.p, _x.state.q, _x.state.r, _x.state.thrust, _x.state.remaining,) = _struct_15d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_15d.pack(_x.state.t, _x.state.x, _x.state.y, _x.state.z, _x.state.roll, _x.state.pitch, _x.state.yaw, _x.state.u, _x.state.v, _x.state.w, _x.state.p, _x.state.q, _x.state.r, _x.state.thrust, _x.state.remaining))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.state is None:
        self.state = hal_quadrotor.msg.State()
      end = 0
      _x = self
      start = end
      end += 120
      (_x.state.t, _x.state.x, _x.state.y, _x.state.z, _x.state.roll, _x.state.pitch, _x.state.yaw, _x.state.u, _x.state.v, _x.state.w, _x.state.p, _x.state.q, _x.state.r, _x.state.thrust, _x.state.remaining,) = _struct_15d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_15d = struct.Struct("<15d")
"""autogenerated by genpy from hal_quadrotor/SetEstimateResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SetEstimateResponse(genpy.Message):
  _md5sum = "38b8954d32a849f31d78416b12bff5d1"
  _type = "hal_quadrotor/SetEstimateResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
bool    success
string  status

"""
  __slots__ = ['success','status']
  _slot_types = ['bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       success,status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SetEstimateResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.success is None:
        self.success = False
      if self.status is None:
        self.status = ''
    else:
      self.success = False
      self.status = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_B.pack(self.success))
      _x = self.status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 1
      (self.success,) = _struct_B.unpack(str[start:end])
      self.success = bool(self.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status = str[start:end].decode('utf-8')
      else:
        self.status = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_B.pack(self.success))
      _x = self.status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 1
      (self.success,) = _struct_B.unpack(str[start:end])
      self.success = bool(self.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status = str[start:end].decode('utf-8')
      else:
        self.status = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
class SetEstimate(object):
  _type          = 'hal_quadrotor/SetEstimate'
  _md5sum = 'e5b0cff35b7ba6b3b27ca50b371e7ab2'
  _request_class  = SetEstimateRequest
  _response_class = SetEstimateResponse
