std_msgs/Header       header        # Time
geometry_msgs/Vector3 position      # reference-frame velocity
geometry_msgs/Vector3 orientation   # reference-frame velocity
geometry_msgs/Vector3 linvelocity   # reference-frame velocity
geometry_msgs/Vector3 angvelocity   # reference-frame velocity
float64 thrust	                    # Thrust force
float64 voltage	                    # Energy remaining (proportion)