"""autogenerated by genpy from hal_quadrotor/State.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class State(genpy.Message):
  _md5sum = "dd7ae38fc9e37befb212bfebfefaf134"
  _type = "hal_quadrotor/State"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 t	    	# Time stamp
float64 x	    	# n-frame X position (X == +East)
float64 y	   		# n-frame Y position (Y == +North)
float64 z	    	# n-frame Z position (Z == +Up)
float64 roll	    # n-frame roll (anti-clockwise about X)
float64 pitch	    # n-frame pitch (anti-clockwise about Y)
float64 yaw	    	# n-frame yaw (anti-clockwise about Z)
float64 u	    	# b-frame X velocity
float64 v	    	# b-frame Y velocity
float64 w	    	# b-frame Z velocity
float64 p	    	# b-frame roll angular velocity
float64 q	    	# b-frame pitch angular velocity
float64 r	    	# b-frame yaw angular velocity
float64 thrust	    # Current thrust force
float64 remaining	# Flight time remaining
"""
  __slots__ = ['t','x','y','z','roll','pitch','yaw','u','v','w','p','q','r','thrust','remaining']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       t,x,y,z,roll,pitch,yaw,u,v,w,p,q,r,thrust,remaining

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(State, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.t is None:
        self.t = 0.
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.u is None:
        self.u = 0.
      if self.v is None:
        self.v = 0.
      if self.w is None:
        self.w = 0.
      if self.p is None:
        self.p = 0.
      if self.q is None:
        self.q = 0.
      if self.r is None:
        self.r = 0.
      if self.thrust is None:
        self.thrust = 0.
      if self.remaining is None:
        self.remaining = 0.
    else:
      self.t = 0.
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.roll = 0.
      self.pitch = 0.
      self.yaw = 0.
      self.u = 0.
      self.v = 0.
      self.w = 0.
      self.p = 0.
      self.q = 0.
      self.r = 0.
      self.thrust = 0.
      self.remaining = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_15d.pack(_x.t, _x.x, _x.y, _x.z, _x.roll, _x.pitch, _x.yaw, _x.u, _x.v, _x.w, _x.p, _x.q, _x.r, _x.thrust, _x.remaining))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 120
      (_x.t, _x.x, _x.y, _x.z, _x.roll, _x.pitch, _x.yaw, _x.u, _x.v, _x.w, _x.p, _x.q, _x.r, _x.thrust, _x.remaining,) = _struct_15d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_15d.pack(_x.t, _x.x, _x.y, _x.z, _x.roll, _x.pitch, _x.yaw, _x.u, _x.v, _x.w, _x.p, _x.q, _x.r, _x.thrust, _x.remaining))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 120
      (_x.t, _x.x, _x.y, _x.z, _x.roll, _x.pitch, _x.yaw, _x.u, _x.v, _x.w, _x.p, _x.q, _x.r, _x.thrust, _x.remaining,) = _struct_15d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_15d = struct.Struct("<15d")
