float64 x	    	# n-frame X position (X == +East)
float64 y	   		# n-frame Y position (Y == +North)
float64 z	    	# n-frame Z position (Z == Up)
float64 roll	    # n-frame roll (anti-clockwise about X)
float64 pitch	    # n-frame pitch (anti-clockwise about Y)
float64 yaw	    	# n-frame yaw (anti-clockwise about Z)
float64 u	    	# b-frame X velocity
float64 v	    	# b-frame Y velocity
float64 w	    	# b-frame Z velocity
float64 p	    	# b-frame roll angular velocity
float64 q	    	# b-frame pitch angular velocity
float64 r	    	# b-frame yaw angular velocity
float64 thrust	    # Current thrust force
float64 voltage	    # Energy remaining (volts)