/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/asymingt/Workspace/Source/crates/src/hal_sensor_altimeter/srv/Configure.srv
 *
 */


#ifndef HAL_SENSOR_ALTIMETER_MESSAGE_CONFIGUREREQUEST_H
#define HAL_SENSOR_ALTIMETER_MESSAGE_CONFIGUREREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hal_sensor_altimeter
{
template <class ContainerAllocator>
struct ConfigureRequest_
{
  typedef ConfigureRequest_<ContainerAllocator> Type;

  ConfigureRequest_()
    : samprate(0.0)
    , sendrate(0.0)  {
    }
  ConfigureRequest_(const ContainerAllocator& _alloc)
    : samprate(0.0)
    , sendrate(0.0)  {
    }



   typedef double _samprate_type;
  _samprate_type samprate;

   typedef double _sendrate_type;
  _sendrate_type sendrate;




  typedef boost::shared_ptr< ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigureRequest_

typedef ::hal_sensor_altimeter::ConfigureRequest_<std::allocator<void> > ConfigureRequest;

typedef boost::shared_ptr< ::hal_sensor_altimeter::ConfigureRequest > ConfigureRequestPtr;
typedef boost::shared_ptr< ::hal_sensor_altimeter::ConfigureRequest const> ConfigureRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hal_sensor_altimeter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hal_sensor_altimeter': ['/home/asymingt/Workspace/Source/crates/src/hal_sensor_altimeter/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4e24855e09a12faffe1d04b21ea96eb";
  }

  static const char* value(const ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4e24855e09a12faULL;
  static const uint64_t static_value2 = 0xffe1d04b21ea96ebULL;
};

template<class ContainerAllocator>
struct DataType< ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hal_sensor_altimeter/ConfigureRequest";
  }

  static const char* value(const ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 samprate\n\
float64 sendrate\n\
";
  }

  static const char* value(const ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.samprate);
      stream.next(m.sendrate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ConfigureRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hal_sensor_altimeter::ConfigureRequest_<ContainerAllocator>& v)
  {
    s << indent << "samprate: ";
    Printer<double>::stream(s, indent + "  ", v.samprate);
    s << indent << "sendrate: ";
    Printer<double>::stream(s, indent + "  ", v.sendrate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAL_SENSOR_ALTIMETER_MESSAGE_CONFIGUREREQUEST_H
