/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/asymingt/Workspace/Source/crates/src/sim/srv/Delete.srv
 *
 */


#ifndef SIM_MESSAGE_DELETE_H
#define SIM_MESSAGE_DELETE_H

#include <ros/service_traits.h>


#include <sim/DeleteRequest.h>
#include <sim/DeleteResponse.h>


namespace sim
{

struct Delete
{

typedef DeleteRequest Request;
typedef DeleteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Delete
} // namespace sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sim::Delete > {
  static const char* value()
  {
    return "9ce56b4e9e54616de25d796dc972a262";
  }

  static const char* value(const ::sim::Delete&) { return value(); }
};

template<>
struct DataType< ::sim::Delete > {
  static const char* value()
  {
    return "sim/Delete";
  }

  static const char* value(const ::sim::Delete&) { return value(); }
};


// service_traits::MD5Sum< ::sim::DeleteRequest> should match 
// service_traits::MD5Sum< ::sim::Delete > 
template<>
struct MD5Sum< ::sim::DeleteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sim::Delete >::value();
  }
  static const char* value(const ::sim::DeleteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sim::DeleteRequest> should match 
// service_traits::DataType< ::sim::Delete > 
template<>
struct DataType< ::sim::DeleteRequest>
{
  static const char* value()
  {
    return DataType< ::sim::Delete >::value();
  }
  static const char* value(const ::sim::DeleteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sim::DeleteResponse> should match 
// service_traits::MD5Sum< ::sim::Delete > 
template<>
struct MD5Sum< ::sim::DeleteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sim::Delete >::value();
  }
  static const char* value(const ::sim::DeleteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sim::DeleteResponse> should match 
// service_traits::DataType< ::sim::Delete > 
template<>
struct DataType< ::sim::DeleteResponse>
{
  static const char* value()
  {
    return DataType< ::sim::Delete >::value();
  }
  static const char* value(const ::sim::DeleteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIM_MESSAGE_DELETE_H
