/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/asymingt/Workspace/Source/crates/src/sim/srv/Pause.srv
 *
 */


#ifndef SIM_MESSAGE_PAUSE_H
#define SIM_MESSAGE_PAUSE_H

#include <ros/service_traits.h>


#include <sim/PauseRequest.h>
#include <sim/PauseResponse.h>


namespace sim
{

struct Pause
{

typedef PauseRequest Request;
typedef PauseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Pause
} // namespace sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sim::Pause > {
  static const char* value()
  {
    return "2ec6f3eff0161f4257b808b12bc830c2";
  }

  static const char* value(const ::sim::Pause&) { return value(); }
};

template<>
struct DataType< ::sim::Pause > {
  static const char* value()
  {
    return "sim/Pause";
  }

  static const char* value(const ::sim::Pause&) { return value(); }
};


// service_traits::MD5Sum< ::sim::PauseRequest> should match 
// service_traits::MD5Sum< ::sim::Pause > 
template<>
struct MD5Sum< ::sim::PauseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sim::Pause >::value();
  }
  static const char* value(const ::sim::PauseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sim::PauseRequest> should match 
// service_traits::DataType< ::sim::Pause > 
template<>
struct DataType< ::sim::PauseRequest>
{
  static const char* value()
  {
    return DataType< ::sim::Pause >::value();
  }
  static const char* value(const ::sim::PauseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sim::PauseResponse> should match 
// service_traits::MD5Sum< ::sim::Pause > 
template<>
struct MD5Sum< ::sim::PauseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sim::Pause >::value();
  }
  static const char* value(const ::sim::PauseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sim::PauseResponse> should match 
// service_traits::DataType< ::sim::Pause > 
template<>
struct DataType< ::sim::PauseResponse>
{
  static const char* value()
  {
    return DataType< ::sim::Pause >::value();
  }
  static const char* value(const ::sim::PauseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIM_MESSAGE_PAUSE_H
